baseURL = "https://hitsz-lug-weekly.pages.dev/"
theme = "bilberry-hugo-theme"
title = "LUG Weekly"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh-cn"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
# Custom CSS / JS modules that will be imported by the template.
# Files are relative to the static/ directory or a URL.
# Files are imported in the order they appear here, after
# theme.css and theme.js, respectively.
css_modules = []
js_modules = []

# Description and meta data for the search engines
author = "HITsz LUG"
description = "HITsz LUG 周报"
keywords = "blog weekly"

# How many articles should be displayed at once?
paginate = 7

# Enable / Disable MathJax
enable_mathjax = false

# Enable / Disable algolia search
algolia_apiKey = "16030625f1a4d0dd3b8aefd794fd4cf1"
algolia_appId = "45CEN6X6AT"
algolia_indexName = "bilberry-hugo-theme"
algolia_search = false
# Set this option to false if you want to search within all articles in all languages at once
algolia_currentLanguageOnly = true

# Enable / Disable comments on the articles via commento
# commentoJsURL = "https://commento.lednerb.de/js/commento.js"

# Enable / Disable Giscus comments
giscus = false
giscusCategory = "[ENTER CATEGORY NAME HERE]"
giscusCategoryId = "[ENTER CATEGORY ID HERE]"
giscusCrossOrigin = "anonymous"
giscusEmitMetadata = "0"
giscusJsUrl = "https://giscus.app/client.js"
giscusLanguage = "en"
giscusMapping = "pathname"
giscusReactions = "1"
giscusRepository = "[ENTER REPO HERE]"
giscusRepositoryId = "[ENTER REPO ID HERE]"
giscusTheme = "light"

# Enable / Disable Utterances comments
utterances = false
utterancesCrossOrigin = "anonymous"
utterancesIssueTerm = "pathname"
utterancesJsUrl = "https://utteranc.es/client.js"
utterancesLabel = "Comment"
utterancesRepository = "[ENTER REPO HERE]"
utterancesTheme = "github-light"

# Media configuration
# let hugo automatically resize and crop your images to the correct sizes
# NB: When enabled the image files get renamed by adding additional information,
#     even if the image has the correct sizes.
resizeImages = true

# Header configuration
# your subtitle if you want to use any
subtitle = "这里是 HITsz LUG 周报，记录每周 LUG 奇闻异录。"

# if you want to use libravatar or gravatar for the header image
# avatarEmail = "code@lednerb.de"

# set an path to the image file you want to use | overwrites avatar by email
customImage = "/assets/logo.svg"

# define the icon you want to use for the overlay for the customImage or avatar.
overlayIcon = "fa-home"

# always display the top navigation (with pages and search) on non-mobile screens
permanentTopNav = true

# always display the top navigation when scrolling
# works only with permanentTopNav = true
stickyNav = false

# show a language chooser in the header
showHeaderLanguageChooser = false

# Content configuration
# Enable an optional pinned page to display at the top of the index
# pinnedPost = "/article/installing-bilberry-theme/"
# Set to true to pin only to the first page, false to all pages
# pinOnlyToFirstPage = true

# enable automatic localization of the article's PublishedDate with momentjs
enableMomentJs = true

# customize the date format | only works if momentjs is disabled | only works with English month names
# you can customize it with the options you find here:
# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02"

# display the estimated reading time for an article
showReadingTime = false

# Minimum word count to display the Table of Contents
tocMinWordCount = 400

# Footer configuration
showFooter = true

# How many articles should be displayed at latest posts in the footer?
# Set to -1 to hide the 'Latest Posts' column
amountLatestPostsInFooter = 7

# How many categories should be displayed in the footer section?
# Set to -1 to hide the 'Categories' column
amountCategoriesInFooter = 7

# show a language chooser in the footer
showFooterLanguageChooser = false

# social media profile urls for the footer links
showSocialMedia = true

# show an archive link in the footer
showArchive = false

# archive grouping: "2006" by year, "2006-01" by month
archiveDateGrouping = "2006-01"

# define your links with FontAwesome 5 (only free icons are supported)
# all icons https://fontawesome.com/icons?d=gallery&m=free
# brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
socialMediaLinks = [
  {link = "https://github.com/hitszlug", icon = "fab fa-github"},
  {link = "https://t.me/hitszlug", icon = "fab fa-telegram"},
  {link = "https://qm.qq.com/cgi-bin/qm/qr?k=EmOyWeZrOaOeSoVrVLoozyKYdvjOia_t", icon = "fab fa-qq"},
]

# credits line configuration
copyrightBy = "CC BY-NC-SA 4.0 by HITsz LUG" 
copyrightUrl = "https://github.com/hitszlug" 
copyrightUseCurrentYear = true # set to true to always display the current year in the copyright
copyrightYearOverride = "2022" 
creditsText = "Bilberry Hugo Theme" 
creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme" 

# customize your available languages for your multi-lingual site
# or delete the [Languages] blog to use the theme with only one supported language
# [Languages]
# [Languages.zh-cn]
# weight = 1

hasCJKLanguage = true

# don't change anything below
[taxonomies]
author = "author"
category = "categories"
series = "series"
tag = "tags"

[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML"]

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
[markup.goldmark.renderer]
# Change to 'true' if you need to render raw HTML within your markdown content
unsafe = false

[markup.tableOfContents]
endLevel = 5
ordered = false
startLevel = 2
